name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_NAME: ApolloExtensions

jobs:
  build:
    name: Build and Test
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: swift build

      - name: Test
        id: test
        run: swift test --enable-code-coverage

      - name: Prepare Code Coverage
        id: prepare-codecov-coverage-report
        if: steps.test.outcome == 'success'
        run: |
          set -o pipefail && \
          xcrun llvm-cov export \
          -format="lcov" \
          --ignore-filename-regex='(Tests)[/\\].*' \
          -instr-profile .build/debug/codecov/default.profdata \
          .build/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}PackageTests \
          > info.lcov

      - name: Upload coverage to Codecov
        if: steps.prepare-codecov-coverage-report.outcome == 'success'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
